<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKU50NUJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKU50NUJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKU50NUJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKU50NUJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKU50NUJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KU50NUJ',
    'container.build_id' => '95d85bf0',
    'container.build_time' => 1617199545,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKU50NUJ');
